/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict-local
 */

import type { StrictSvgProps } from '../../types/StrictSvgProps';

import * as React from 'react';
import { errorMsg } from '../../shared/logUtils';
import { isSvgPropAllowed } from '../../shared/isSvgPropAllowed';
// $FlowFixMe[cannot-resolve-module]
import { merge } from 'react-strict-dom/runtime';

// $FlowFixMe[unclear-type]
function validateStrictProps(props: any) {
  Object.keys(props).forEach((key) => {
    const isValid = isSvgPropAllowed(key);
    if (!isValid) {
      errorMsg(`invalid prop "${key}"`);
      delete props[key];
    }
  });
}

export function createStrictDOMSvgComponent<T, P extends StrictSvgProps>(
  TagName: string,
  defaultStyle: StrictSvgProps['style']
): component(ref?: React.RefSetter<T>, ...P) {
  // NOTE: `debug-style` is not generated by `stylex.create`
  // so it needs a type-cast
  const debugStyle = {
    $$css: true,
    'debug::name': `svg-${TagName}` as $FlowFixMe
  };

  component Component(ref?: React.RefSetter<T>, ...props: P) {
    /**
     * get host props
     */
    const { style, ...hostProps } = props;
    validateStrictProps(hostProps);

    if (props.role != null) {
      // "presentation" synonym has wider browser support
      // $FlowFixMe[incompatible-type]
      hostProps.role = props.role === 'none' ? 'presentation' : props.role;
    }

    /**
     * get host style props
     */
    // $FlowFixMe[incompatible-type]
    const hostStyleProps = merge([debugStyle, defaultStyle, style]);

    /**
     * Construct tree
     *
     * Intentional flow error as we are asking for a more specific type
     * than React itself.
     */
    const element = (
      <TagName {...hostProps} {...hostStyleProps} ref={ref as $FlowFixMe} />
    );
    return element;
  }

  // eslint-disable-next-line no-unreachable
  Component.displayName = `svg.${TagName}`;
  return Component;
}
