/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [
    {
      dirName: 'learn',
      type: 'autogenerated'
    }
  ],
  apiSidebar: [
    {
      dirName: 'api',
      type: 'autogenerated'
    }
  ],
  contributeSidebar: [
    {
      dirName: 'contribute',
      type: 'autogenerated'
    }
  ]
};

export default sidebars;
