name: performance

on: [pull_request]

jobs:
  compressed-size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: necolas/compressed-size-action@master
      with:
        name: "runtime library"
        build-script: "build"
        pattern: "./packages/react-strict-dom/dist/{dom/index.js,dom/runtime.js,native/index.js}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  benchmarks:
    name: benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: 'Setup temporary files'
      run: |
        echo "BASE_SHA=$(echo ${{ github.event.pull_request.base.sha }} | cut -c1-8)" >> $GITHUB_ENV
        echo "PATCH_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8)" >> $GITHUB_ENV
        echo "BASELINE_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "PATCH_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "PR_COMMENT=$(mktemp)" >>  $GITHUB_ENV
    - name: 'Benchmark: baseline'
      run: |
        git checkout ${{ github.event.pull_request.base.sha }}
        npm install --loglevel error
        npm run build
        if npm run benchmarks -w react-strict-dom -- ${{ env.BASELINE_JSON }}; then
          echo "Benchmark ran successfully on base branch"
        else
          echo "{}" > ${{ env.BASELINE_JSON }}  # Empty JSON as default
          echo "Benchmark script not found on base branch, using default values"
        fi
    - name: 'Benchmark: patch'
      run: |
        git checkout ${{ github.event.pull_request.head.sha }}
        npm install
        npm install --loglevel error
        npm run build
        npm run benchmarks -w react-strict-dom -- ${{ env.PATCH_JSON }}
        echo "Benchmark ran successfully on patch branch"
    - name: 'Collect results'
      run: |
        echo "### workflow: benchmarks (native)" >> pr_comment
        echo "Comparison of benchmark test results, measured in operations per second (higher is faster.)" >> pr_comment
        node packages/react-strict-dom/benchmarks/display.js ${{ env.BASELINE_JSON }} ${{ env.PATCH_JSON }} >> pr_comment
        cat pr_comment > ${{ env.PR_COMMENT }}
    - name: 'Post comment'
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: require('fs').readFileSync('${{ env.PR_COMMENT }}').toString()
          });
